"""Add skill assessment and report comments

Revision ID: 091cf9e1473d
Revises: d2fb8d6d1016
Create Date: 2026-04-30 03:03:09.981526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '091cf9e1473d'
down_revision: Union[str, Sequence[str], None] = 'd2fb8d6d1016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicable_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_name'), 'skill', ['name'], unique=True)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'MANAGER', 'TEACHER', 'KITCHEN', 'UTILITY', name='staffrole'), nullable=False),
    sa.Column('clearance_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='clearancelevel'), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_email'), 'team', ['email'], unique=True)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Enum('BABY', 'PLAYGROUP', 'PP1', 'PP2', name='levelcode'), nullable=False),
    sa.Column('section', sa.Enum('A', 'B', name='classsection'), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.Column('house', sa.Enum('SUNFLOWER', 'BLUEBELL', 'DAFFODIL', 'MARIGOLD', name='housename'), nullable=False),
    sa.Column('uses_transport', sa.Boolean(), nullable=False),
    sa.Column('transport_route', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('homeroom_teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['homeroom_teacher_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='attendancestatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('allergies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doctor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doctor_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('parent_guardian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('EXCEEDING', 'MEETING', 'APPROACHING', 'NEEDS_INTERVENTION', name='skillrating'), nullable=False),
    sa.Column('teacher_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_assessment_skill_id'), 'skill_assessment', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_assessment_student_id'), 'skill_assessment', ['student_id'], unique=False)
    op.create_table('student_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_supply_student_id'), 'student_supply', ['student_id'], unique=False)
    op.create_table('termly_report_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=False),
    sa.Column('homeroom_teacher_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('principal_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_termly_report_comment_student_id'), 'termly_report_comment', ['student_id'], unique=False)
    op.create_unique_constraint('uq_termly_comment_student_term_year', 'termly_report_comment', ['student_id', 'term', 'academic_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_termly_comment_student_term_year', 'termly_report_comment', type_='unique')
    op.drop_index(op.f('ix_termly_report_comment_student_id'), table_name='termly_report_comment')
    op.drop_table('termly_report_comment')
    op.drop_index(op.f('ix_student_supply_student_id'), table_name='student_supply')
    op.drop_table('student_supply')
    op.drop_index(op.f('ix_skill_assessment_student_id'), table_name='skill_assessment')
    op.drop_index(op.f('ix_skill_assessment_skill_id'), table_name='skill_assessment')
    op.drop_table('skill_assessment')
    op.drop_table('parent_guardian')
    op.drop_table('medical_history')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_team_email'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_skill_name'), table_name='skill')
    op.drop_table('skill')
    # ### end Alembic commands ###
