"""Add disciplinary log

Revision ID: 2f57db901db6
Revises: 091cf9e1473d
Create Date: 2026-04-30 03:23:49.119258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f57db901db6'
down_revision: Union[str, Sequence[str], None] = '091cf9e1473d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinary_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_taken', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'MAJOR', name='infractionseverity'), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinary_log_student_id'), 'disciplinary_log', ['student_id'], unique=False)
    op.drop_constraint(op.f('uq_termly_comment_student_term_year'), 'termly_report_comment', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_termly_comment_student_term_year'), 'termly_report_comment', ['student_id', 'term', 'academic_year'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_disciplinary_log_student_id'), table_name='disciplinary_log')
    op.drop_table('disciplinary_log')
    # ### end Alembic commands ###
