"""Add hashed_password to Team

Revision ID: 7db996a253bd
Revises: 
Create Date: 2026-04-25 21:16:59.005368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7db996a253bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('team', sa.Column('hashed_password', sa.String(), nullable=True))
    
    # 2. Populate existing rows with a placeholder bcrypt hash
    # This hash corresponds to "change_me_immediately" (you can change later)
    op.execute(
        "UPDATE team SET hashed_password = "
        "'$2b$12$LJ3m4ys3GZfnYMz8kVsKaOqkPqFQOv5gYkK6rGXm0X8IqH4ZHf9Oe' "
        "WHERE hashed_password IS NULL"
    )
    
    # 3. Now make the column NOT NULL
    op.alter_column('team', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'hashed_password')
    # ### end Alembic commands ###
