"""
Student is the central entity of the management system.
A student belongs to one SchoolClass and AcademicLevel.
The student ID is generated by the student_id_generator service
using the format SOIS-{level_code}-{stream_code}-{seq:03d}.
Legacy relationships (parent_guardians, medical_history) are retained for
compatibility with any data migrated from the previous schema.
"""
from sqlmodel import SQLModel, Field, Relationship
from typing import Optional, List, TYPE_CHECKING
from datetime import date

if TYPE_CHECKING:
    from app.models.academic_level import AcademicLevel
    from app.models.class_ import SchoolClass
    from app.models.route import Route
    from app.models.student_route import StudentRoute
    from app.models.previous_education import PreviousEducation
    from app.models.medical_information import MedicalInformation
    from app.models.parent_info import ParentInfo
    from app.models.document import Document
    from app.models.club import StudentClub
    from app.models.attendance import Attendance
    from app.models.skill_assessment import SkillAssessment
    from app.models.student_supply import StudentSupply
    from app.models.discipline import DisciplinaryLog
    from app.models.parent_guardian import ParentGuardian
    from app.models.medical import MedicalHistory
    from app.models.sibling_group import SiblingGroup


class Student(SQLModel, table=True):
    __tablename__ = "student"

    id: Optional[int] = Field(default=None, primary_key=True)
    student_id: str = Field(unique=True, index=True)
    first_name: str
    last_name: str
    date_of_birth: date
    age_months: Optional[int] = None
    gender: Optional[str] = None
    is_active: bool = Field(default=True)
    stream: Optional[str] = None            # e.g. "East", "West"

    academic_level_id: Optional[int] = Field(default=None, foreign_key="academic_level.id")
    class_id: Optional[int] = Field(default=None, foreign_key="school_class.id")
    transport_route_id: Optional[int] = Field(default=None, foreign_key="route.id")
    sibling_group_id: Optional[int] = Field(default=None, foreign_key="sibling_group.id")
    is_reported_back: bool = Field(default=False)

    # Primary relationships
    academic_level: Optional["AcademicLevel"] = Relationship(back_populates="students")
    school_class: Optional["SchoolClass"] = Relationship(back_populates="students")
    transport_route: Optional["Route"] = Relationship()
    student_routes: List["StudentRoute"] = Relationship(back_populates="student")
    sibling_group: Optional["SiblingGroup"] = Relationship(back_populates="students")
    previous_education: Optional["PreviousEducation"] = Relationship(back_populates="student")
    medical_info: Optional["MedicalInformation"] = Relationship(back_populates="student")
    parents: List["ParentInfo"] = Relationship(back_populates="student")
    documents: List["Document"] = Relationship(back_populates="student")
    clubs: List["StudentClub"] = Relationship(back_populates="student")

    # Academic / operational relationships
    attendance_records: List["Attendance"] = Relationship(back_populates="student")
    skill_assessments: List["SkillAssessment"] = Relationship(back_populates="student")
    supplies: List["StudentSupply"] = Relationship(back_populates="student")
    disciplinary_logs: List["DisciplinaryLog"] = Relationship(back_populates="student")

    # Legacy relationships (kept for backward compatibility)
    parent_guardians: List["ParentGuardian"] = Relationship(back_populates="student")
    medical_history: Optional["MedicalHistory"] = Relationship(back_populates="student")

    def compute_age_months(self) -> int:
        today = date.today()
        return (today.year - self.date_of_birth.year) * 12 + (today.month - self.date_of_birth.month)
